# Generated by Django 2.1.7 on 2019-03-02 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='max_points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
