# Generated by Django 2.1.7 on 2019-04-09 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='exam_sheets.Task'),
        ),
    ]
