# Generated by Django 2.1.7 on 2019-03-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0002_auto_20190302_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='assigned_points',
            field=models.IntegerField(default=0),
        ),
    ]
