# Generated by Django 2.1.7 on 2019-03-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0004_auto_20190303_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='exam_sheet_id',
            new_name='exam_sheet',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='examsheet',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='exam_sheet_id',
            new_name='exam_sheet',
        ),
    ]
