# Generated by Django 2.1.7 on 2019-03-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0005_auto_20190303_1920'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('exam_sheet', 'user')},
        ),
    ]
