# Generated by Django 2.1.7 on 2019-03-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0007_auto_20190304_2140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
