# Generated by Django 2.1.7 on 2019-03-04 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0008_auto_20190304_2158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
    ]
