# Generated by Django 2.1.7 on 2019-03-04 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0009_auto_20190304_2238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('exam_sheet', 'user')},
        ),
    ]
