# Generated by Django 2.1.7 on 2019-03-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0013_auto_20190305_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='final_grade',
            new_name='achieved_points',
        ),
        migrations.AddField(
            model_name='exam',
            name='is_passed',
            field=models.CharField(choices=[('PASSED', 'Passed'), ('NOT PASSED', 'Not passed'), ('PENDING', 'pending')], default='PENDING', max_length=30),
        ),
    ]
