# Generated by Django 2.1.7 on 2019-03-06 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0014_auto_20190306_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam_sheets.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exam_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='exam_sheets.ExamSheet'),
        ),
    ]
