# Generated by Django 2.1.7 on 2019-03-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0019_task_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='exam',
        ),
        migrations.AddField(
            model_name='answer',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_sheets.Exam'),
        ),
    ]
