# Generated by Django 2.1.7 on 2019-03-10 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0020_auto_20190310_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_sheets.Exam'),
        ),
    ]
