# Generated by Django 2.1.7 on 2019-03-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0023_auto_20190311_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_points',
            field=models.IntegerField(default=0),
        ),
    ]
